# Site settings.

# Without a clear rule enforced, both title and name are used.
title: µOS++ IIIe / POSIX++
name: µOS++ IIIe / POSIX++
description: The third edition of µOS++ / POSIX++, an open source system, written in C++.
motto: “Perfekt ist nicht gut genug”
icon: wall-e-icon.png

email: ilg@livius.net

destination: _site
exclude:
  - README.md
  - 'CONTRIBUTING*.md'
  - 'MIGRATE-*.md'
  - 'CODE_OF_CONDUCT*.md'
  - .github
  - '*.command'
  - '*.webloc'
  - '*.pptx'
  - Gemfile
  - Gemfile.lock
  - vendor
  - scripts


# Used in sitemap.xml.
url: "http://micro-os-plus.github.io" # the base hostname & protocol for your site.

# The subpath of your site, e.g. /blog (note the leading slash and the
# absence of a trailing slash).
baseurl: ""

# This timezone is used to display post dates and last modified messages.
timezone: UTC

encoding: utf-8

# Default permalink used for posts.
permalink: /blog/:year/:month/:day/:title/

# Build settings.
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Warning: paginator retired in Jekyll 3!
# Make this larger, probably 5 is a good choice.
# paginate: 2
# paginate_path: "/blog/page:num/"

# The number of links added to the 'Latest news' box.
latest-news-pages: 4

# Currently disabled, since it generates incomplete content.
# Use manually written RSS feed.xml.
#   - jekyll-feed
# {% feed_meta %} in head.html

# jekyll-last-modified-at is not available on GitHub Pages.
gems:
  - jekyll-last-modified-at
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

# Not yet functional
#  - jekyll-multiple-languages

# If you want to use pagination, you should add jekyll-paginate into gems
# and make sure it is in front of jekyll-multiple-languages

# All languages used
# languages:          ['en', 'pt']

# If not configured, the first item of languages will be used as the default.
# language_default:   'en'

# Custom definitions.

# References to the project associated with the web.
github-username:  ilg-ul
github-project-name: micro-os-plus/micro-os-plus-iii
github-project-url: http://github.com/micro-os-plus/micro-os-plus-iii
github-this-project-url: https://github.com/micro-os-plus/micro-os-plus.github.io-source
github-this-project-branch: master
sourceforge-project-url: http://sourceforge.net/projects/micro-os-plus

# Change it to refer to project's page
# facebook-url: https://facebook.com/ilg-ul/
facebook-page: https://facebook.com/micro.os.plus/

twitter-id: micro_os_plus
twitter-url: http://twitter.com/micro_os_plus

# If you have one, define it here.
google-analytics-id: UA-16767008-14
google-site-verification: NT_y3tqI_8mrd8gYA_FDWHT2-tkJExOC6KBkSnyZx6c

# Disable it if no site footer is needed.
# custom-footer-content: content/site-custom-footer.markdown

# jekyll-toc-generator
tocTopTag: h2
minItemsToShowToc: 3
useExistingAnchors: true

css-date: 201608151703

# Content copyright. Update it to your needs.
copyright-message: "© 2017 Liviu Ionescu"
